### PR TITLE
Bugs galore

### PR DESCRIPTION
**Pull request by gianlazaro**
Due to several bugs arising, I had to rewrite a lot of the logic that it might've taken me to long to clear the ticket. 
### **Please start using NPM RUN SERVER-DEV while testing. It runs both the server and webpack --watch simultaneously.**
- Changed button text according to BRD spec
- Created a controller to manage API data by ignoring empty pages UP TO 7 PAGES (from 2) and remove duplicates
- A loading circle has been added to aid with user experience
- On initial load, answers are taken from the questions endpoint call. Anytime a user adds a comment, a small answers endpoint will be called to minimize huge network requests.
- Updated localstorage logic to fix a bug that would revert state to its previous value
- Removed logic of pulling all questions to the server
- Removed the ability of my component to disable scrolling due to a bug and also user experience
- Changed the shape of data because, for some reason, answers object in the answers api is different from the answers object in the questions api
- Updated the index.js for the server to clean it up and be more adaptable to where it runs (using path)
- Added NPM RUN SERVER-DEV to run the server and webpack simultaneously

### CODE REVIEW

**Comment by kbinhnguyen** [comment]
[Review of PR #65](https://trello.com/c/mH5gbAX7/117-review-of-pr-65)

**Comment by carsonliu1** [comment]
For the functions with async await inside of the promise chains, writing async and await and not actually returning the result of the await may defeat the purpose of writing async/await. Promise chains ( .then) already return promises so I don't think async await is actually needed. If you decided to use async/await you can open a try/catch block inside of the then statement that its in, rather than chaining another .then after it.

**Comment by kbinhnguyen** [comment]
[THE API is ever changing 🤬 Fixing this..thing.. again.. <Link inside>](https://trello.com/c/hOyyvJnS/115-the-api-is-ever-changing-%F0%9F%A4%AC-fixing-thisthing-again)

**Comment by gianlazaro** [comment]
@carsonliu1 You're absolutely right! I probably left it off from an earlier solution I had where I wanted to await for a value to resolve before continuing on. Nonetheless, like you said, I couldve just fully committed to a try catch block or just separate them in then blocks.

For the solution I ended up committing, I removed any async functions (and awaits) and just returned the axios.get to get the promise.

**Comment by gianlazaro** [comment]
Since I was using curly brackets, there's no implicit return so I had to add return keywords to pass the result along the chain. Probably could've gotten by without it but it's not a bad thing to have.

**Comment by carsonliu1** [comment]
Looks good now!

**Pull request merged**
