### PR TITLE
Checkout completed

### PR DESCRIPTION
**Pull request by kbinhnguyen**
Features achieved in this ticket: https://trello.com/c/OYnXRGVJ

### CODE REVIEW

**Comment by kbinhnguyen** [comment]
[Complete 'Add to Cart' button](https://trello.com/c/OYnXRGVJ/66-complete-add-to-cart-button)

**Comment by kbinhnguyen** [comment]
[Complete 'Add to Cart' button](https://trello.com/c/OYnXRGVJ/66-complete-add-to-cart-button)

**Comment by kbinhnguyen** [comment]
[Complete 'Add to Cart' button](https://trello.com/c/OYnXRGVJ/66-complete-add-to-cart-button)

**Comment by gianlazaro** [comment]
Excellent work!

**Pull request merged**
