### PR TITLE
Reorganize and set up responsive styling design for Image Gallery section (GridChild #1 of Grid #1 in Overview)

### PR DESCRIPTION
**Pull request by kbinhnguyen**
Also in this ticket: fixed styling logic flaw in Expanded View from yesterday (setting a negative z-index on an element will disable cursor styling on that element)

### CODE REVIEW

**Comment by kbinhnguyen** [comment]
[Reorganize and set up responsive styling design for Image Gallery section (GridChild #1 of Grid #1 in Overview)](https://trello.com/c/WJWzehMj/111-reorganize-and-set-up-responsive-styling-design-for-image-gallery-section-gridchild-1-of-grid-1-in-overview)

**Comment by gianlazaro** [comment]
Great work on creating a responsive grid! 🎉 

**Notes:**
Whenever you use z-index in any of your subcomponents, it is recommended to add `isolation: isolate` on the parent component. z-index takes into account all the other z-index values in the whole document otherwise. There's no one stopping anyone from putting 99999 for z-index on their component and break your implementation, for example.  

With the `isolation: isolate` property, it creates a new stacking context and isolates your subcomponents relative to only your parent component.

I see you have started working on implementing styled-components into your component. Well done! I think it is better to put all styles at the bottom (even after the export statement) since whenever I open a file, I expect to see the logic of the component and not the styles. It's all preference though and I'm not too worried about it. Hopefully, later on, we can start moving it to separate files.


_Please let me know when change(s) have been made through Slack or if you have any other questions 👍_

**Comment by kbinhnguyen** [comment]
@gianlazaro: Thanks so much for pointing out the `isolation` CSS property. I went to read up on it and it was extremely helpful to know! When working on my components last evening I did run into issues with others' components overflowing on top of mine 😅 - so hopefully that won't happen again.

I incorporated your suggestion of moving the majority of the styling logic toward the end of each file, with the exception of the styling objects that I pass directly as an attribute to my React components (shouldn't use a variable before defining it!) Will get to cleaning up styling syntax more thoroughly later.

I also deleted `client-dev` completely from our NPM run scripts to prevent our team from accidentally running it.

Let me know if you have any other suggestions!

**Comment by gianlazaro** [comment]
It looks good to me! 🎉 

Keep it up, @kbinhnguyen !

**Pull request merged**
