### PR TITLE
Unit tests for Questions And Answers subcomponents

### PR DESCRIPTION
**Pull request by gianlazaro**
Tests by subcomponents:
- **AnswerModal**
  - This should check if the answer modal backdrop is shown 
  - This should check if the form fields are required
- **QABox**
  - This should render the Question and Answer component
- **QAListItem**
  - on helpful vote button press, disable helpful vote button
  - on load more answers button press, collapse answers text is shown
- **QAWrapper**
  - This should render the QA wrapper
  - This should update the questions provided a wrong search term
- **QuestionModal**
  - This should check if the modal backdrop is shown
  - This should check if the form fields are required
- **SearchBar**
  - This should show a placeholder text in the Searchbar
  - This should set the controlled value of the Searchbar based on the state

### CODE REVIEW

**Comment by gianlazaro** [comment]
Link to ticket: https://trello.com/c/RfVGEdHG

**Comment by kbinhnguyen** [comment]
Wow very thorough unit tests for your individual components here! Way to step up the testing game by making full use of the Jest DOM matchers API!

Just some small comments:
1) As mentioned in an earlier PR, you no longer have to specify `@jest-environment jsdom` at the beginning of each file because we now have a jest config file which specifies the default environment to jsdom already.

2) In some of your tests you imported many matchers from the Testing Library Jest DOM and methods from the Testing Library React that were not used in those specific test files, which makes it a bit difficult mentally to keep track of which matchers/methods will be used. For example, `waitFor` was always imported but never used because you did not have any tests for asynchronous events. Or in certain tests I saw that you imported `toBeEmptyDOMElement` and was anticipating to see its use in your tests but it didn't show up. It would be great if you could clean these up.

3) This morning our team discussed the use of `import` vs. `require` statements and we agreed to use `import` / `export default` statements to handle data objects from separate files to stay consistent within each test, and to stay up to date with [ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). I think it'd be good to review this.

But great job in implementing all of these!

**Comment by gianlazaro** [comment]
@kbinhnguyen I have cleaned up the test files from the excellent points that you had. 

I have also reassessed on if I should use the screen module or not. I ended up rewriting all tests without it, and deconstructed render to get the queries out.

Cheers! 

Link to the most recent commit: https://github.com/ShamWow-FEC/rfp2205-shamwows/pull/58/commits/62945d11d8d6f2dc55546353949d1aac35260bef

**Comment by kbinhnguyen** [comment]
@gianlazaro Everything looks good to me! Superb work! 🎉

**Comment by kbinhnguyen** [comment]
[Writing tests for QA component](https://trello.com/c/RfVGEdHG/93-writing-tests-for-qa-component)

**Pull request merged**
